#!/bin/bash

SOURCE_TEX="thesis.tex"
VARBOSE_FLAG=0

function spin {
	local pid=$1
	local delay=0.1
	sp="/-\|"
	i=1
	while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
		sleep $delay
		char="${sp:i++%${#sp}:1}"
		printf " [%s]\r" ${char}
	done
}

function usage {
  cat <<EOM
Usage: $(basename "$0") [OPTION] [SOURCE DIRECTORY]...
  -h        Display help
  -f VALUE  Name of latex source file (Default: ${SOURCE_TEX})
  -v        Display latexmk log
EOM
  exit 2
}

while getopts ":f:hv" OPT; do
  case $OPT in
	f)  SOURCE_TEX=$OPTARG
		;;
	v)  VARBOSE_FLAG=1
		;;
	h)  usage
		;;
	\?) usage
		;;
  esac
done

shift `expr $OPTIND - 1`
if [ $# -ne 1 ]; then
	usage
fi

SOURCE_DIR=$1
if [ ! -e $SOURCE_DIR/$SOURCE_TEX ]; then
	echo $SOURCE_DIR/$SOURCE_TEX" does not exist."
	usage
fi

cd $SOURCE_DIR
TMPDIR=$(mktemp -d tmp.XXXXXX)
TMPTEX=$(mktemp tmp-XXXXXX)
mv $TMPTEX $TMPTEX.tex
TMPTEX=$TMPTEX.tex

DOCUMENT_CLASS=$(grep documentclass $SOURCE_TEX)
cat <<EOF > $TMPTEX
${DOCUMENT_CLASS}
\usepackage{comment}
\excludecomment{figure}
\let\endfigure\relax
\excludecomment{table}
\let\endtable\relax
\excludecomment{jabstract}
\let\endjabstract\relax
\excludecomment{eabstract}
\let\endeabstract\relax
EOF
cat $SOURCE_TEX | sed 's|\\maketitle||g' | sed 's|\\tableofcontents||g' >> $TMPTEX

if [ $VARBOSE_FLAG = 1 ]; then
	latexmk -pdfdvi -f $TMPTEX -outdir=$TMPDIR
else
	latexmk -pdfdvi -f $TMPTEX -outdir=$TMPDIR > /dev/null 2>&1 & spin $!
fi

PDF=$(ls $TMPDIR | grep '.*pdf$')
pdfinfo $TMPDIR/$PDF | grep Pages | awk '{print "Page count: " $2}'

mkdir -p out
cp $TMPDIR/$PDF out/pagecount.pdf
rm -rf $TMPDIR $TMPTEX
