#!/bin/bash

SOURCE_TEX="thesis.tex"
VARBOSE_FLAG=0
BACHELOR_MODE=0

function spin {
    tput civis
	local pid=$1
	local delay=0.1
	sp="/-\|"
	i=1
	while [ "$(ps a | awk '{print $1}' | grep $pid)" ]; do
		sleep $delay
		char="${sp:i++%${#sp}:1}"
		printf "Now compiling...%s\r" ${char}
	done
	printf "                  \r"
    tput cnorm
}

function usage {
  cat <<EOM
Usage: $(basename "$0") [OPTION] [SOURCE DIRECTORY]...
  -h        Display help
  -b        Bachelor mode (Default: Master mode)
  -f VALUE  Name of latex source file (Default: ${SOURCE_TEX})
  -v        Display latexmk log
EOM
  exit 2
}

while getopts ":f:bhv" OPT; do
  case $OPT in
	f)  SOURCE_TEX=$OPTARG
		;;
	b)	BACHELOR_MODE=1
		;;
	v)  VARBOSE_FLAG=1
		;;
	h)  usage
		;;
	\?) usage
		;;
  esac
done

shift `expr $OPTIND - 1`
if [ $# -ne 1 ]; then
	usage
fi

SOURCE_DIR=$1
if [ ! -e $SOURCE_DIR/$SOURCE_TEX ]; then
	echo $SOURCE_DIR/$SOURCE_TEX" does not exist."
	usage
fi

cd $SOURCE_DIR
TMPDIR=$(mktemp -d tmp.XXXXXX)
TMPTEX=$(mktemp tmp-XXXXXX)
mv $TMPTEX $TMPTEX.tex
TMPTEX=$TMPTEX.tex

if [ $BACHELOR_MODE = 0 ]; then
	sed -e '/\\begin{figure}/,/\\end{figure}/d' -e '/\\begin{table}/,/\\end{table}/d' -e '/\\begin{eabstract}/,/\\end{eabstract}/d' -e '/\\begin{jabstract}/,/\\end{jabstract}/d' -e 's|\\maketitle||g' -e 's|\\tableofcontents||g' $SOURCE_TEX > $TMPTEX
else
	sed -e '/\\begin{figure}/,/\\end{figure}/d' -e '/\\begin{table}/,/\\end{table}/d' -e '/\\begin{eabstract}/,/\\end{eabstract}/d' -e '/\\begin{acknowledgements}/,/\\end{acknowledgements}/d' -e 's|\\bibliography{.*}||g' -e 's|\\maketitle||g' -e 's|\\tableofcontents||g' $SOURCE_TEX > $TMPTEX
fi

if [ $VARBOSE_FLAG = 1 ]; then
	latexmk -pdfdvi -f $TMPTEX -outdir=$TMPDIR
else
	latexmk -pdfdvi -f $TMPTEX -outdir=$TMPDIR > /dev/null 2>&1 & spin $!
fi

PDF=$(ls $TMPDIR | grep '.*pdf$')
pdfinfo $TMPDIR/$PDF | grep Pages | awk '{print "Page count: " $2}'

mkdir -p out
cp $TMPDIR/$PDF out/pagecount.pdf
rm -rf $TMPDIR $TMPTEX
